"""Add OAuth fields to user model

Revision ID: 9a0f477a0322
Revises: 
Create Date: 2025-11-03 23:27:03.796954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '9a0f477a0322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('suggested_feeds', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('rules', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_templates_id'), 'feed_templates', ['id'], unique=False)
    op.create_index(op.f('ix_feed_templates_name'), 'feed_templates', ['name'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('conditions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('scraper_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scrape_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=True),
    sa.Column('ocr_languages', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('ocr_preprocessing', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('css_selectors', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('xpath_rules', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('clean_html', sa.Boolean(), nullable=True),
    sa.Column('extract_images', sa.Boolean(), nullable=True),
    sa.Column('extract_links', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('auth_credentials', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('custom_headers', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('run_nlp', sa.Boolean(), nullable=True),
    sa.Column('apply_rules', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_destinations_id'), 'scraper_destinations', ['id'], unique=False)
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('extracted_images', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('extracted_links', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True),
    sa.Column('ocr_metadata', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_errors', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['scraper_destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_content_id'), 'scraped_content', ['id'], unique=False)
    op.create_table('article_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_errors', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_article_metadata_id'), 'article_metadata', ['id'], unique=False)
    op.alter_column('articles', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('articles', 'readability_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('articles', 'readability_label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('articles', 'writing_style',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_link'), 'articles', ['link'], unique=True)
    op.alter_column('user_preferences', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'picture')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.alter_column('user_preferences', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_articles_link'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.alter_column('articles', 'writing_style',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'readability_label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'readability_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('articles', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_article_metadata_id'), table_name='article_metadata')
    op.drop_table('article_metadata')
    op.drop_index(op.f('ix_scraped_content_id'), table_name='scraped_content')
    op.drop_table('scraped_content')
    op.drop_index(op.f('ix_scraper_destinations_id'), table_name='scraper_destinations')
    op.drop_table('scraper_destinations')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_feed_templates_name'), table_name='feed_templates')
    op.drop_index(op.f('ix_feed_templates_id'), table_name='feed_templates')
    op.drop_table('feed_templates')
    # ### end Alembic commands ###
